version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-orders
    environment:
      POSTGRES_DB: ordersystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - orders-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-orders
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - postgres
    networks:
      - orders-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-orders
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - orders-network

volumes:
  postgres_data:

networks:
  orders-network:
    driver: bridge 